---
# Source: springboot1/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: syinq-stage-main-service
  namespace: stage
  labels:
    app: syinq-stage-main-service
    business-unit: syinq
    component: api
    instance: syinq-stage-main-service-app
    managed-by: helm
    name: syinq-stage-main-service
    owner: coolops
    part-of: syinq
    project: syinq
    version: v1
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: syinq-stage-main-service
      business-unit: syinq
      component: api
      instance: syinq-stage-main-service-app
      managed-by: helm
      name: syinq-stage-main-service
      owner: coolops
      part-of: syinq
      project: syinq
      version: v1
---
# Source: springboot1/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: stage
  name: syinq-stage-main-service
spec:
  type: NodePort
  selector:
    app: syinq-stage-main-service
    business-unit: syinq
    component: api
    instance: syinq-stage-main-service-app
    managed-by: helm
    name: syinq-stage-main-service
    owner: coolops
    part-of: syinq
    project: syinq
    version: v1
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
# Source: springboot1/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syinq-stage-main-service
  namespace: stage
  labels:
    app: syinq-stage-main-service
    business-unit: syinq
    component: api
    instance: syinq-stage-main-service-app
    managed-by: helm
    name: syinq-stage-main-service
    owner: coolops
    part-of: syinq
    project: syinq
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: syinq-stage-main-service
      business-unit: syinq
      component: api
      instance: syinq-stage-main-service-app
      managed-by: helm
      name: syinq-stage-main-service
      owner: coolops
      part-of: syinq
      project: syinq
      version: v1
  template:
    metadata:
      labels:
        app: syinq-stage-main-service
        business-unit: syinq
        component: api
        instance: syinq-stage-main-service-app
        managed-by: helm
        name: syinq-stage-main-service
        owner: coolops
        part-of: syinq
        project: syinq
        version: v1
    spec:
      containers:
      - name: syinq-stage-main-service
        image: "831926620158.dkr.ecr.ap-south-2.amazonaws.com/syinq-be-ecr-stage-aps-2-main-service:{{IMAGE_TAG}}"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
        env:
        - name: CF_ACCESS_KEY_ID
          value: ""
        - name: CF_PRIVATE_KEY
          value: ""
        ports:
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: "500m"
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 180
          timeoutSeconds: 20
          periodSeconds: 60
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 180
          timeoutSeconds: 20
          periodSeconds: 30
          failureThreshold: 5
      nodeSelector:
        type: spot-memory
      # tolerations:
      # - effect: NoSchedule
      #   key: key
      #   operator: Equal
      #   value: value
---
# Source: springboot1/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syinq-stage-main-ondemand-service
  namespace: stage
  labels:
    app: syinq-stage-main-service
    business-unit: syinq
    component: api
    instance: syinq-stage-main-service-app
    managed-by: helm
    name: syinq-stage-main-service
    owner: coolops
    part-of: syinq
    project: syinq
    version: v1
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: syinq-stage-main-service
      business-unit: syinq
      component: api
      instance: syinq-stage-main-service-app
      managed-by: helm
      name: syinq-stage-main-service
      owner: coolops
      part-of: syinq
      project: syinq
      version: v1
  template:
    metadata:
      labels:
        app: syinq-stage-main-service
        business-unit: syinq
        component: api
        instance: syinq-stage-main-service-app
        managed-by: helm
        name: syinq-stage-main-service
        owner: coolops
        part-of: syinq
        project: syinq
        version: v1

    spec:
      containers:
      - name: syinq-stage-main-service
        image: "831926620158.dkr.ecr.ap-south-2.amazonaws.com/syinq-be-ecr-stage-aps-2-main-service:{{IMAGE_TAG}}"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
        env:
        - name: CF_ACCESS_KEY_ID
          value: ""
        - name: CF_PRIVATE_KEY
          value: ""
        ports:
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: "500m"
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 180
          timeoutSeconds: 20
          periodSeconds: 60
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 180
          timeoutSeconds: 20
          periodSeconds: 30
          failureThreshold: 5
      nodeSelector:
        type: On-demand
      # tolerations:
      # - effect: NoSchedule
      #   key: key
      #   operator: Equal
      #   value: value
---
# Source: springboot1/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: syinq-stage-main-service
  namespace: stage
  labels:
    app: syinq-stage-main-service
    business-unit: syinq
    component: api
    instance: syinq-stage-main-service-app
    managed-by: helm
    name: syinq-stage-main-service
    owner: coolops
    part-of: syinq
    project: syinq
    version: v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: syinq-stage-main-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
